### ISSUE TITLE
Containerize slate-server scripts

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [slateci/slate-server-scripts#1]
The SLATE API server is being containerized. Explore how to do the same here.

**Comment by adamhgriffith-uofu** [comment]
Going to look at [K8s cron jobs](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) and implementing them natively in the upcoming [SLATE API Helm Chart](https://github.com/slateci/helm-slate-api).

**Comment by adamhgriffith-uofu** [comment]
Work on the base image containing all dependencies is being tracked at https://github.com/slateci/docker-images/issues/23.

**Comment by adamhgriffith-uofu** [comment]
@sthapa how do my edits look on the [scripts](https://github.com/slateci/slate-server-scripts/tree/feature/1-containerize-slate-server-scripts/scripts)?
* They are meant to fit into [cronjobs.yml](https://github.com/slateci/helm-slate-api/blob/develop/templates/cronjobs.yml)
* I should probably set up a `docker-entrypoint.sh` for [Dockerfile](https://github.com/slateci/slate-server-scripts/blob/feature/1-containerize-slate-server-scripts/Dockerfile) to mimic what K8s is feeding in for local development.

**Comment by sthapa** [comment]
The changes look fine from my view
